apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-api
  namespace: default
spec:
  template:
    metadata:
      name: prime-api-pos
    spec:
      containers:
        - image:  github.com/vagababov/prime-server
      containerConcurrency: 15

---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-api
  namespace: default
spec:
  template:
    metadata:
      name: prime-api-neg
    spec:
      containers:
        - image:  github.com/vagababov/prime-server
          args: ["--negate", "true"]
      containerConcurrency: 15
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-api
  namespace: default
spec:
  template:
    metadata:
      name: prime-api-neg
    spec:
      containers:
        - image:  github.com/vagababov/prime-server
          args: ["--negate", "true"]
      containerConcurrency: 15
  traffic:
  - tag: current
    revisionName: prime-api-neg
    percent: 75
  - tag: candidate
    revisionName: prime-api-pos
    percent: 25
  - tag: latest
    latestRevision: true
    percent: 0
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prime-grpc
  namespace: default
spec:
  template:
    spec:
      containers:
        - image:  github.com/vagababov/prime-server
          ports:
            - name: h2c
              containerPort: 8081

